# define kinematic solver for MoveIt to use
arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
  position_only_ik: true # ik = inverse kinematic
  # since only 3 DOF, ask ik solver to only define pos without orientation